-- ================================================================
-- LocDailyMar - TAHAP 21
-- Promo & Harga Lanjutan
-- Jalankan satu kali di Supabase Dashboard > SQL Editor.
-- Aman dijalankan ulang (idempotent).
-- ================================================================

begin;

alter table public.products
    add column if not exists promo_name text,
    add column if not exists promo_type text,
    add column if not exists promo_value numeric(16,2);

update public.products
set promo_name = coalesce(nullif(btrim(promo_name),''),'Promo Produk'),
    promo_type = case
        when promo_type in ('fixed_price','percentage') then promo_type
        else 'fixed_price'
    end,
    promo_value = case
        when promo_value is not null then promo_value
        when promo_price is not null then promo_price
        else 0
    end;

alter table public.products
    alter column promo_name set default 'Promo Produk',
    alter column promo_name set not null,
    alter column promo_type set default 'fixed_price',
    alter column promo_type set not null,
    alter column promo_value set default 0,
    alter column promo_value set not null;

alter table public.products
    drop constraint if exists products_promo_type_valid;
alter table public.products
    add constraint products_promo_type_valid
    check (promo_type in ('fixed_price','percentage'));

alter table public.products
    drop constraint if exists products_promo_dates_valid;
alter table public.products
    add constraint products_promo_dates_valid
    check (
        promo_start_date is null
        or promo_end_date is null
        or promo_start_date <= promo_end_date
    );

create or replace function public.ldm_normalize_product_promo()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.promo_name := coalesce(nullif(btrim(new.promo_name),''),'Promo Produk');
    new.promo_type := coalesce(nullif(new.promo_type,''),'fixed_price');
    new.promo_value := greatest(coalesce(new.promo_value,0),0);
    new.promo_min_qty := greatest(coalesce(new.promo_min_qty,1),1);

    if new.promo_start_date is not null
       and new.promo_end_date is not null
       and new.promo_start_date > new.promo_end_date then
        raise exception 'Tanggal selesai promo tidak boleh lebih awal daripada tanggal mulai.';
    end if;

    if new.promo_type = 'percentage' then
        if new.promo_active
           and (new.promo_value <= 0 or new.promo_value >= 100) then
            raise exception 'Diskon persen harus lebih dari 0 dan kurang dari 100.';
        end if;
        new.promo_price := round(
            greatest(coalesce(new.sale_price,0),0)
            * (1 - new.promo_value / 100),
            2
        );
    else
        if new.promo_value <= 0 and new.promo_price is not null then
            new.promo_value := greatest(new.promo_price,0);
        end if;
        new.promo_price := new.promo_value;
    end if;

    if new.promo_active then
        if coalesce(new.sale_price,0) <= 0 then
            raise exception 'Harga normal harus lebih besar dari 0 sebelum promo diaktifkan.';
        end if;
        if coalesce(new.promo_price,0) <= 0 then
            raise exception 'Harga promo harus lebih besar dari 0.';
        end if;
        if new.promo_price >= new.sale_price then
            raise exception 'Harga promo harus lebih rendah daripada harga normal.';
        end if;
    end if;

    return new;
end;
$$;

drop trigger if exists trg_stage21_normalize_product_promo on public.products;
create trigger trg_stage21_normalize_product_promo
before insert or update of
    sale_price,
    promo_active,
    promo_name,
    promo_type,
    promo_value,
    promo_price,
    promo_min_qty,
    promo_start_date,
    promo_end_date
on public.products
for each row
execute function public.ldm_normalize_product_promo();

-- Riwayat perubahan harga untuk audit Owner/Admin.
create table if not exists public.product_pricing_history (
    id bigint generated by default as identity primary key,
    store_id uuid not null references public.stores(id) on delete cascade,
    product_id uuid not null references public.products(id) on delete cascade,
    changed_by uuid references auth.users(id) on delete set null,
    old_sale_price numeric(16,2),
    new_sale_price numeric(16,2),
    old_promo jsonb not null default '{}'::jsonb,
    new_promo jsonb not null default '{}'::jsonb,
    changed_at timestamptz not null default now()
);

create index if not exists product_pricing_history_store_product_idx
on public.product_pricing_history(store_id,product_id,changed_at desc);

alter table public.product_pricing_history enable row level security;
revoke all on public.product_pricing_history from anon;
revoke insert,update,delete on public.product_pricing_history from authenticated;
grant select on public.product_pricing_history to authenticated;

drop policy if exists product_pricing_history_select_management
on public.product_pricing_history;
create policy product_pricing_history_select_management
on public.product_pricing_history
for select
to authenticated
using (
    store_id = public.ldm_current_store_id()
    and public.ldm_current_role() in ('owner','admin')
);

create or replace function public.ldm_log_product_pricing_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if old.sale_price is not distinct from new.sale_price
       and old.promo_active is not distinct from new.promo_active
       and old.promo_name is not distinct from new.promo_name
       and old.promo_type is not distinct from new.promo_type
       and old.promo_value is not distinct from new.promo_value
       and old.promo_price is not distinct from new.promo_price
       and old.promo_min_qty is not distinct from new.promo_min_qty
       and old.promo_start_date is not distinct from new.promo_start_date
       and old.promo_end_date is not distinct from new.promo_end_date then
        return new;
    end if;

    insert into public.product_pricing_history(
        store_id,product_id,changed_by,old_sale_price,new_sale_price,old_promo,new_promo
    ) values (
        new.store_id,
        new.id,
        auth.uid(),
        old.sale_price,
        new.sale_price,
        jsonb_build_object(
            'aktif',old.promo_active,'nama',old.promo_name,'type',old.promo_type,
            'value',old.promo_value,'hargaPromo',old.promo_price,'minQty',old.promo_min_qty,
            'tglMulai',old.promo_start_date,'tglSelesai',old.promo_end_date
        ),
        jsonb_build_object(
            'aktif',new.promo_active,'nama',new.promo_name,'type',new.promo_type,
            'value',new.promo_value,'hargaPromo',new.promo_price,'minQty',new.promo_min_qty,
            'tglMulai',new.promo_start_date,'tglSelesai',new.promo_end_date
        )
    );
    return new;
end;
$$;

drop trigger if exists trg_stage21_log_product_pricing on public.products;
create trigger trg_stage21_log_product_pricing
after update of
    sale_price,
    promo_active,
    promo_name,
    promo_type,
    promo_value,
    promo_price,
    promo_min_qty,
    promo_start_date,
    promo_end_date
on public.products
for each row
execute function public.ldm_log_product_pricing_change();

-- Menyimpan field promo baru dari compatibility cache dataBarang.
create or replace function public.ldm_save_advanced_promos_bulk(p_products jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_store_id uuid;
    v_item jsonb;
    v_promo jsonb;
    v_product_id uuid;
    v_barcode text;
    v_name text;
    v_active boolean;
    v_promo_name text;
    v_type text;
    v_value numeric(16,2);
    v_price numeric(16,2);
    v_min_qty numeric(16,3);
    v_start date;
    v_end date;
    v_count integer := 0;
begin
    v_store_id := public.ldm_current_store_id();
    if v_store_id is null then
        raise exception 'Store profile tidak ditemukan.';
    end if;
    if public.ldm_current_role() <> 'owner' then
        raise exception 'Hanya Owner yang dapat mengubah promo dan harga.';
    end if;
    if p_products is null or jsonb_typeof(p_products) <> 'array' then
        raise exception 'p_products harus berupa JSON array.';
    end if;

    for v_item in select value from jsonb_array_elements(p_products)
    loop
        v_product_id := null;
        begin
            v_product_id := nullif(v_item->>'id','')::uuid;
        exception when invalid_text_representation then
            v_product_id := null;
        end;

        v_barcode := nullif(btrim(coalesce(v_item->>'barcode','')),'');
        v_name := nullif(btrim(coalesce(v_item->>'nama',v_item->>'name','')),'');
        v_promo := coalesce(v_item->'promo','{}'::jsonb);
        v_active := coalesce(nullif(v_promo->>'aktif','')::boolean,false);
        v_promo_name := coalesce(nullif(btrim(v_promo->>'nama'),''),'Promo Produk');
        v_type := case when v_promo->>'type' = 'percentage' then 'percentage' else 'fixed_price' end;
        v_value := coalesce(
            nullif(v_promo->>'value','')::numeric,
            nullif(v_promo->>'persen','')::numeric,
            nullif(v_promo->>'hargaPromo','')::numeric,
            0
        );
        v_price := coalesce(nullif(v_promo->>'hargaPromo','')::numeric,0);
        v_min_qty := greatest(coalesce(nullif(v_promo->>'minQty','')::numeric,1),1);
        v_start := nullif(v_promo->>'tglMulai','')::date;
        v_end := nullif(v_promo->>'tglSelesai','')::date;

        if v_type = 'fixed_price' and v_value <= 0 then
            v_value := v_price;
        end if;

        update public.products
        set promo_active = v_active,
            promo_name = v_promo_name,
            promo_type = v_type,
            promo_value = greatest(v_value,0),
            promo_price = greatest(v_price,0),
            promo_min_qty = v_min_qty,
            promo_start_date = v_start,
            promo_end_date = v_end
        where store_id = v_store_id
          and deleted_at is null
          and (
              (v_product_id is not null and id = v_product_id)
              or (v_product_id is null and v_barcode is not null and barcode = v_barcode)
              or (
                  v_product_id is null and v_barcode is null and v_name is not null
                  and lower(name) = lower(v_name)
                  and 1 = (
                      select count(*) from public.products p2
                      where p2.store_id = v_store_id
                        and p2.deleted_at is null
                        and lower(p2.name) = lower(v_name)
                  )
              )
          );

        if found then v_count := v_count + 1; end if;
    end loop;
    return v_count;
end;
$$;

revoke all on function public.ldm_save_advanced_promos_bulk(jsonb) from public,anon;
grant execute on function public.ldm_save_advanced_promos_bulk(jsonb) to authenticated;

create or replace function public.ldm_sync_products_stage21(p_products jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_count integer;
begin
    v_count := public.ldm_sync_products_stage20(p_products);
    perform public.ldm_save_advanced_promos_bulk(p_products);
    return v_count;
end;
$$;

revoke all on function public.ldm_sync_products_stage21(jsonb) from public,anon;
grant execute on function public.ldm_sync_products_stage21(jsonb) to authenticated;

commit;
